### ISSUE TITLE
How should Promise.all() handle an empty array?

### ISSUE THREAD

**Issue by kixxauth** [kixxauth/iou#5]
Currently it returns a promise that never resolves, which passes the spec tests, but does not seem correct.

**Comment by brkattk** [comment]
Found this while waiting around for a build to complete: https://github.com/jakearchibald/es6-promise/blob/master/test/extension-test.js#L420-L425

**Comment by kixxauth** [comment]
Cool, thanks @brkattk 

So, I pulled the latest version of the Promises A+ tests and they still passed despite IOU not resolving a Promise.all() with an empty Array.

So I duplicated the test from es6-promise and changed the implementation to match.

https://github.com/kixxauth/iou/commit/44f63160079569415b599413e3798402bb67959f
